---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~0.18
  name: prometheus-node-exporter
  namespace: monitoring
spec:
  chart:
    name: prometheus-node-exporter
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 1.8.1
  releaseName: prometheus-node-exporter

  values:
    image:
      repository: prom/node-exporter
      tag: v0.18.1
    resources:
      limits:
        cpu: 200m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 30Mi
    tolerations:
      - operator: "Exists"
    extraArgs:
      - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
      - --path.rootfs=/host/rootfs
    extraHostVolumeMounts:
    - name: rootfs
      hostPath: /
      mountPath: /host/rootfs
      readOnly: true
    service:
      annotations: {} # Need to set this to blank as the upstream chart defaults to setting the Prometheus scrape annotation.
