---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.controller: semver:~0.30
    flux.weave.works/tag.default-backend: semver:~1.5
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    name: nginx-ingress
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 1.34.3
  releaseName: ingress-nginx

  values:
    controller:
      image:
        repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
        tag: 0.31.1
      config:
        access-log-path: "/dev/stdout"
        error-log-level: "warn"
        error-log-path: "/dev/stdout"
        proxy-buffer-size: "128k"
        proxy-connect-timeout: "60"
        proxy-read-timeout: "60"
        server-tokens: "false"
      hostNetwork: true
      daemonSet:
        useHostPort: true
      kind: DaemonSet
      updateStrategy:
        rollingUpdate:
          maxUnavailable: 1
        type: RollingUpdate
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
    defaultBackend:
      image:
        repository: k8s.gcr.io/defaultbackend-amd64
        tag: "1.5"
    podSecurityPolicy:
      enabled: false
