---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: general-purpose-retain
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
