---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: general-purpose-delete
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
