---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    flux.weave.works/automated: "false"
  name: sealed-secrets-helm-operator
  namespace: flux
spec:
  chart:
    name: helm-operator
    repository: https://charts.fluxcd.io
    version: 1.0.2
  releaseName: sealed-secrets-helm-operator
  targetNamespace: sealed-secrets
  values:
    image:
      repository: docker.io/fluxcd/helm-operator
      tag: 1.1.0
    allowNamespace: sealed-secrets
    helm:
      versions: "v3"
    rbac:
      create: true
    clusterRole:
      create: true
    prometheus:
      enabled: true
